server:
  port: 8080

spring:
  application:
    name: avito-balance-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/balances
  jpa:
    hibernate:
      ddl-auto: update